// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw2YC16nF-VS2_8c-JaDs6rERktdO09pg',
    appId: '1:253131687143:web:83f192f115a080459b8e42',
    messagingSenderId: '253131687143',
    projectId: 'fir-recycle-769a8',
    authDomain: 'fir-recycle-769a8.firebaseapp.com',
    storageBucket: 'fir-recycle-769a8.appspot.com',
    measurementId: 'G-K9T9HTF8KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoq36Yo7m2S_AwthWNrJRXO1Gc0V5TX80',
    appId: '1:253131687143:android:f955c9525a866eae9b8e42',
    messagingSenderId: '253131687143',
    projectId: 'fir-recycle-769a8',
    storageBucket: 'fir-recycle-769a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGnzgNgwtR25RIcJu4MedLTvLns8iT3o',
    appId: '1:253131687143:ios:fcafbafd32a2c2459b8e42',
    messagingSenderId: '253131687143',
    projectId: 'fir-recycle-769a8',
    storageBucket: 'fir-recycle-769a8.appspot.com',
    iosClientId: '253131687143-5ssees0dd26nv6e9jkg99hcat8bmjvme.apps.googleusercontent.com',
    iosBundleId: 'com.example.varyRecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGGnzgNgwtR25RIcJu4MedLTvLns8iT3o',
    appId: '1:253131687143:ios:fcafbafd32a2c2459b8e42',
    messagingSenderId: '253131687143',
    projectId: 'fir-recycle-769a8',
    storageBucket: 'fir-recycle-769a8.appspot.com',
    iosClientId: '253131687143-5ssees0dd26nv6e9jkg99hcat8bmjvme.apps.googleusercontent.com',
    iosBundleId: 'com.example.varyRecycle',
  );
}
